[package]
name = "shigure-test"
edition = "2021"
version.workspace = true

[dependencies]
shigure-parser = { path = "../shigure-parser" }
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
